package com.qa.ai.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;

/**
 * A single test case generated by Claude from a user story.
 *
 * For type="ui"  → steps list is populated, request/assertions are null.
 * For type="api" → request + assertions are populated, steps are null.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class TestCase {

    private String id;
    private String title;
    private String type;        // "ui" | "api"
    private List<String> tags;
    private String expected;    // plain-English expected outcome

    // UI test fields
    private List<TestStep> steps;

    // API test fields
    private ApiRequest request;
    private List<ApiAssertion> assertions;

    public TestCase() {}

    // -------- Getters & Setters --------

    public String getId()      { return id;       }
    public void setId(String id) { this.id = id; }

    public String getTitle()   { return title;    }
    public void setTitle(String title) { this.title = title; }

    public String getType()    { return type;     }
    public void setType(String type) { this.type = type; }

    public List<String> getTags() { return tags;  }
    public void setTags(List<String> tags) { this.tags = tags; }

    public String getExpected() { return expected; }
    public void setExpected(String expected) { this.expected = expected; }

    public List<TestStep> getSteps() { return steps; }
    public void setSteps(List<TestStep> steps) { this.steps = steps; }

    public ApiRequest getRequest() { return request; }
    public void setRequest(ApiRequest request) { this.request = request; }

    public List<ApiAssertion> getAssertions() { return assertions; }
    public void setAssertions(List<ApiAssertion> assertions) { this.assertions = assertions; }

    public boolean isUiTest()  { return "ui".equalsIgnoreCase(type);  }
    public boolean isApiTest() { return "api".equalsIgnoreCase(type); }

    @Override
    public String toString() {
        return String.format("[%s] %s (%s)", id, title, type);
    }
}
