package com.qa.ai.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Collections;
import java.util.List;

/**
 * Represents a single step in a UI test case generated by Claude.
 *
 * Supported actions:
 *   navigate          — go to a URL
 *   fill              — type text into an input (target = CSS selector, value = text)
 *   click             — click an element (target = CSS selector)
 *   assert_visible    — assert element is visible (target = CSS selector)
 *   assert_text       — assert element contains text (target = CSS selector, value = expected text)
 *   assert_url_contains — assert current URL contains fragment (target = fragment)
 *   wait_for          — wait for element to appear (target = CSS selector)
 *   select            — select an option from a dropdown (target = CSS selector, value = option text)
 *
 * Self-healing: if target fails, PlaywrightExecutor tries each entry in fallback_targets before giving up.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class TestStep {

    private String action;
    private String target;
    private String value;

    /** Optional fallback selectors tried in order when the primary target times out. */
    private List<String> fallback_targets;

    public TestStep() {}

    public TestStep(String action, String target, String value) {
        this.action = action;
        this.target = target;
        this.value  = value;
    }

    public String getAction() { return action; }
    public void setAction(String action) { this.action = action; }

    public String getTarget() { return target; }
    public void setTarget(String target) { this.target = target; }

    public String getValue() { return value; }
    public void setValue(String value) { this.value = value; }

    public List<String> getFallbackTargets() {
        return fallback_targets != null ? fallback_targets : Collections.emptyList();
    }
    public void setFallback_targets(List<String> fallback_targets) {
        this.fallback_targets = fallback_targets;
    }

    @Override
    public String toString() {
        return String.format("Step[action=%s, target=%s, value=%s]", action, target, value);
    }
}