package com.qa.ai.executor;

import com.microsoft.playwright.*;
import com.microsoft.playwright.options.LoadState;
import com.microsoft.playwright.options.WaitForSelectorState;
import com.qa.ai.claude.SelfHealSuggester;
import com.qa.ai.config.ConfigManager;
import com.qa.ai.config.SensitiveDataMasker;
import com.qa.ai.config.TestDataResolver;
import com.qa.ai.model.TestCase;
import com.qa.ai.model.TestStep;
import com.qa.ai.pages.PageRegistry;
import com.qa.ai.reporter.AgentActivity;
import io.qameta.allure.Allure;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.testng.Assert;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Executes UI test cases generated by Claude using Playwright Java.
 *
 * Improvements applied:
 *   F — reads browser/timeout settings from ConfigManager (config.properties)
 *   B — self-healing: tries fallback_targets + PageRegistry fallbacks on TimeoutError
 *   C — rich failure diagnostics: DOM snapshot, console log, current URL, stack trace
 *
 * PRE-REQUISITE (first run only):
 *   mvn exec:java -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install chromium"
 */
public class PlaywrightExecutor implements AutoCloseable {

    private static final Logger log = LogManager.getLogger(PlaywrightExecutor.class);

    // F — read from config.properties
    private static final boolean HEADLESS   = ConfigManager.get().getBoolean("headless", true);
    private static final int TIMEOUT_MS     = ConfigManager.get().getInt("timeout.ms", 10_000);
    private static final String BROWSER_KEY = ConfigManager.get().getString("browser", "chromium");

    private Playwright playwright;
    private Browser browser;
    private BrowserContext context;
    private Page page;
    private Path harPath;

    // Accumulated console messages for diagnostics
    private final List<String> consoleMessages = new ArrayList<>();

    // -------------------------------------------------------------------------
    // LIFECYCLE
    // -------------------------------------------------------------------------

    public void open() {
        log.debug("Launching Playwright {} (headless={})", BROWSER_KEY, HEADLESS);
        playwright = Playwright.create();
        BrowserType browserType = switch (BROWSER_KEY.toLowerCase()) {
            case "firefox" -> playwright.firefox();
            case "webkit"  -> playwright.webkit();
            default        -> playwright.chromium();
        };
        BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions().setHeadless(HEADLESS);
        if (BROWSER_KEY.equalsIgnoreCase("chromium") || BROWSER_KEY.equalsIgnoreCase("chrome")) {
            // In Docker (especially under Rosetta x86 emulation on Apple Silicon):
            //   --disable-dev-shm-usage : redirects Chromium's shared memory to /tmp, avoiding
            //                             /dev/shm size limits and Rosetta JS-engine crashes.
            //   --no-sandbox            : required in containers running as root (no user namespace).
            //   --disable-gpu           : headless containers have no GPU; skips unnecessary init.
            launchOptions.setArgs(java.util.List.of(
                    "--disable-dev-shm-usage",
                    "--no-sandbox",
                    "--disable-gpu"
            ));
        }
        browser = browserType.launch(launchOptions);

        // HAR recording — written to temp file, attached to Allure on failure
        try {
            harPath = Files.createTempFile("playwright-har-", ".har");
        } catch (java.io.IOException e) {
            throw new java.io.UncheckedIOException("Failed to create HAR temp file", e);
        }
        context = browser.newContext(new Browser.NewContextOptions()
                .setRecordHarPath(harPath)
                .setViewportSize(1280, 800));
        context.setDefaultTimeout(TIMEOUT_MS);
        page = context.newPage();

        // C — collect browser console messages for failure diagnostics
        page.onConsoleMessage(msg -> consoleMessages.add(
                String.format("[%s] %s", msg.type().toUpperCase(), msg.text())));

        log.debug("Browser ({}) and page ready — timeout={}ms", BROWSER_KEY, TIMEOUT_MS);
    }

    @Override
    public void close() {
        if (context != null) context.close();   // flushes HAR to harPath
        if (browser != null) browser.close();
        if (playwright != null) playwright.close();
        log.debug("Browser closed");
    }

    // -------------------------------------------------------------------------
    // EXECUTE A TEST CASE
    // -------------------------------------------------------------------------

    public void execute(TestCase testCase) {
        log.info("Executing UI test: {}", testCase);

        Allure.step("Test: " + testCase.getTitle(), () -> {
            List<TestStep> steps = testCase.getSteps();
            if (steps == null || steps.isEmpty()) {
                Assert.fail("Test case has no steps: " + testCase.getId());
            }

            try {
                for (TestStep step : steps) {
                    executeStep(step, testCase.getId());
                }
                log.info("UI test PASSED: {}", testCase.getId());

            } catch (AssertionError | PlaywrightException e) {
                // Do NOT close the context here — doing so would break all subsequent tests
                // that share this executor within the same @BeforeTest block, causing a cascade
                // of TargetClosedErrors.  Screenshot/DOM/cookies are attached from the live page;
                // HAR is skipped for this failure (the context is flushed in close() later).
                attachRichFailureDiagnostics(testCase.getId(), e);
                log.error("UI test FAILED: {} — {}", testCase.getId(), e.getMessage());
                throw e;
            }
        });
    }

    // -------------------------------------------------------------------------
    // STEP DISPATCH
    // -------------------------------------------------------------------------

    private void executeStep(TestStep step, String testId) {
        String action = step.getAction();

        // E — resolve ${VAR} placeholders from test-data.properties
        String target = TestDataResolver.get().resolve(step.getTarget());
        String value  = TestDataResolver.get().resolve(step.getValue());

        // A — resolve logical page-object name to CSS selector (e.g. "login_button" → "#login-button")
        String resolved = PageRegistry.allSelectors().get(target);
        if (resolved != null) {
            AgentActivity.get().recordLocatorResolved(target, resolved);
        } else {
            AgentActivity.get().recordUnknownTarget(target);
        }
        final String resolvedTarget = resolved != null ? resolved : target;

        log.debug("Step → action={} target={} value={}", action, resolvedTarget, value);

        Allure.step(String.format("%s: %s", action, resolvedTarget), () -> {
            executeWithFallback(action, resolvedTarget, value, step.getFallbackTargets(), testId);
            attachStepScreenshot(action, resolvedTarget);
        });
    }

    /**
     * B — Self-healing: runs the action on the primary target.
     * On TimeoutError tries each fallback (step-level, then PageRegistry) before re-throwing.
     */
    private void executeWithFallback(String action, String primaryTarget,
                                     String value, List<String> stepFallbacks, String testId) {
        List<String> candidates = buildCandidateList(primaryTarget, stepFallbacks);

        PlaywrightException lastEx = null;
        for (int i = 0; i < candidates.size(); i++) {
            String selector = candidates.get(i);
            try {
                dispatch(action, selector, value);
                if (i > 0) {
                    log.warn("Self-healing: '{}' succeeded with fallback selector '{}'", action, selector);
                    AgentActivity.get().recordSelfHeal(testId, action, primaryTarget, selector);
                    Allure.addAttachment(
                            "Self-Heal: " + action,
                            "text/plain",
                            new ByteArrayInputStream(
                                    ("Primary: " + primaryTarget + "\nHealed with: " + selector)
                                    .getBytes(StandardCharsets.UTF_8)),
                            ".txt");
                }
                return; // success
            } catch (PlaywrightException e) {
                if (!isTimeoutOrNotFound(e)) throw e; // non-timeout → fail immediately
                lastEx = e;
                if (i < candidates.size() - 1) {
                    log.warn("Self-healing: '{}' failed on '{}', trying fallback #{}", action, selector, i + 1);
                }
            }
        }

        // All candidates exhausted — ask Claude to suggest repair (human-in-the-loop)
        log.error("Self-healing exhausted all {} candidates for '{}' on '{}'",
                candidates.size(), action, primaryTarget);
        try {
            String domSnapshot = page != null ? page.content() : "";
            SelfHealSuggester.suggest(testId, primaryTarget, action, domSnapshot);
        } catch (Exception suggestionEx) {
            log.debug("SelfHealSuggester skipped: {}", suggestionEx.getMessage());
        }

        throw lastEx; // all candidates exhausted
    }

    private List<String> buildCandidateList(String primary, List<String> stepFallbacks) {
        List<String> list = new ArrayList<>();
        list.add(primary);
        list.addAll(stepFallbacks);
        // PageRegistry fallbacks (from Page Object Model)
        List<String> registryFallbacks = PageRegistry.allFallbacks().getOrDefault(primary, List.of());
        registryFallbacks.forEach(f -> { if (!list.contains(f)) list.add(f); });
        return list;
    }

    private boolean isTimeoutOrNotFound(PlaywrightException e) {
        String msg = e.getMessage();
        if (msg == null) return false;
        return msg.contains("Timeout") || msg.contains("timeout") ||
               msg.contains("waiting for selector") || msg.contains("not found");
    }

    // -------------------------------------------------------------------------
    // ACTION DISPATCH
    // -------------------------------------------------------------------------

    private void dispatch(String action, String target, String value) {
        switch (action) {
            case "navigate"            -> navigate(target);
            case "fill"                -> fill(target, value);
            case "click"               -> click(target);
            case "select"              -> select(target, value);
            case "assert_visible"      -> assertVisible(target);
            case "assert_text"         -> assertText(target, value);
            case "assert_url_contains" -> assertUrlContains(target);
            case "wait_for"            -> waitFor(target);
            case "assert_accessible"   -> assertAccessible();
            default -> throw new IllegalArgumentException(
                    "Unknown action '" + action + "' — should have been caught by validator");
        }
    }

    // -------------------------------------------------------------------------
    // INDIVIDUAL ACTIONS
    // -------------------------------------------------------------------------

    private void navigate(String url) {
        log.debug("navigate → {}", url);
        // navigate() already waits for "load" event internally — waitForLoadState() after
        // it is redundant and doubles the timeout consumption on slow networks (Firefox/Rosetta).
        page.navigate(url);
    }

    private void fill(String selector, String value) {
        log.debug("fill {} = {}", selector, value);
        page.waitForSelector(selector, new Page.WaitForSelectorOptions()
                .setState(WaitForSelectorState.VISIBLE));
        page.fill(selector, value);
    }

    private void click(String selector) {
        log.debug("click {}", selector);
        page.waitForSelector(selector, new Page.WaitForSelectorOptions()
                .setState(WaitForSelectorState.VISIBLE));
        page.click(selector);
        // After navigation-triggering clicks (links, form submits) the browser starts loading
        // a new page.  Without an explicit wait, the next step's waitForSelector can race with
        // page initialisation and crash Chromium under Rosetta x86 emulation.
        //
        // waitForLoadState(DOMCONTENTLOADED) is safe for all browsers:
        //   • On non-navigation clicks it returns in <1 ms (DOM already content-loaded).
        //   • On navigation clicks it waits for the new page's DOM to parse.
        //
        // Explicit TIMEOUT_MS cap prevents WebKit from hanging indefinitely when
        // DOMContentLoaded doesn't fire for a specific page in a specific network condition.
        // Errors are swallowed — if the page is not ready, the next step's waitForSelector
        // will produce a clean, actionable failure.
        try {
            page.waitForLoadState(LoadState.DOMCONTENTLOADED,
                    new Page.WaitForLoadStateOptions().setTimeout(TIMEOUT_MS));
        } catch (Exception e) {
            log.debug("post-click waitForLoadState skipped: {}", e.getMessage());
        }
    }

    private void select(String selector, String optionText) {
        log.debug("select {} → {}", selector, optionText);
        page.selectOption(selector, new com.microsoft.playwright.options.SelectOption()
                .setLabel(optionText));
    }

    private void assertVisible(String selector) {
        log.debug("assert_visible {}", selector);
        // waitForSelector throws TimeoutError if not found — enables self-healing fallback
        page.waitForSelector(selector, new Page.WaitForSelectorOptions()
                .setState(WaitForSelectorState.VISIBLE));
    }

    private void assertText(String selector, String expectedText) {
        log.debug("assert_text {} contains '{}'", selector, expectedText);
        // waitForSelector first so TimeoutError triggers self-healing if selector is wrong
        page.waitForSelector(selector, new Page.WaitForSelectorOptions()
                .setState(WaitForSelectorState.VISIBLE));
        String actual = page.locator(selector).textContent();
        Assert.assertTrue(actual != null && actual.contains(expectedText),
                "Expected '" + selector + "' to contain '" + expectedText +
                "' but was: '" + actual + "'");
    }

    private void assertUrlContains(String fragment) {
        log.debug("assert_url_contains '{}'", fragment);
        String currentUrl = page.url();
        Assert.assertTrue(currentUrl.contains(fragment),
                "Expected URL to contain '" + fragment + "' but was: '" + currentUrl + "'");
    }

    private void waitFor(String selector) {
        log.debug("wait_for {}", selector);
        page.waitForSelector(selector, new Page.WaitForSelectorOptions()
                .setState(WaitForSelectorState.VISIBLE));
    }

    /**
     * Runs a basic accessibility audit using in-browser JavaScript evaluation.
     *
     * Checks:
     *   1. Page has at least one landmark element (main, nav, header, footer) or ARIA role
     *   2. All images have alt attributes (WCAG 1.1.1)
     *   3. Form inputs have associated labels (WCAG 1.3.1)
     *   4. Page has a title (WCAG 2.4.2)
     *
     * Attaches a violation summary to Allure for visibility.
     * This is a lightweight alternative to axe-core for offline/headless environments.
     */
    @SuppressWarnings("unchecked")
    private void assertAccessible() {
        log.debug("assert_accessible — running in-browser a11y audit");

        // Run audit via page.evaluate() — returns JSON-serialisable results
        String script = """
            (() => {
              const violations = [];
              // 1. Check for page title
              if (!document.title || document.title.trim() === '') {
                violations.push('Missing page title (WCAG 2.4.2)');
              }
              // 2. Check for landmark elements
              const landmarks = document.querySelectorAll('main, [role=main], nav, [role=navigation], header, footer');
              if (landmarks.length === 0) {
                violations.push('No landmark elements found (main/nav/header/footer) — WCAG 1.3.6');
              }
              // 3. Check images for alt attributes
              const imgsWithoutAlt = Array.from(document.querySelectorAll('img:not([alt])'));
              if (imgsWithoutAlt.length > 0) {
                violations.push('Images missing alt attribute (' + imgsWithoutAlt.length + ' found) — WCAG 1.1.1');
              }
              // 4. Check form inputs for labels
              const inputs = Array.from(document.querySelectorAll('input:not([type=hidden]):not([type=submit]):not([type=button])'));
              const unlabelled = inputs.filter(inp => {
                if (inp.getAttribute('aria-label') || inp.getAttribute('aria-labelledby') || inp.getAttribute('title')) return false;
                const id = inp.id;
                if (id && document.querySelector('label[for="' + id + '"]')) return false;
                if (inp.closest('label')) return false;
                return true;
              });
              if (unlabelled.length > 0) {
                violations.push('Form inputs without accessible labels (' + unlabelled.length + ' found) — WCAG 1.3.1');
              }
              return { violations: violations, title: document.title, url: window.location.href };
            })()
            """;

        Object result = page.evaluate(script);
        String report = result != null ? result.toString() : "(no result)";
        log.info("assert_accessible result: {}", report);

        // Extract violation count for assertion
        boolean hasViolations = report.contains("violations=[") && !report.contains("violations=[]");

        // Attach report to Allure regardless of pass/fail
        Allure.addAttachment("A11y Audit Report", "text/plain",
                new ByteArrayInputStream(report.getBytes(StandardCharsets.UTF_8)), ".txt");

        if (hasViolations) {
            Assert.fail("Accessibility audit found violations on " + page.url() + ":\n" + report);
        }
        log.info("assert_accessible PASSED — no violations detected on {}", page.url());
    }

    // -------------------------------------------------------------------------
    // C — RICH FAILURE DIAGNOSTICS
    // -------------------------------------------------------------------------

    private void attachRichFailureDiagnostics(String testId, Throwable cause) {
        // 1. Screenshot (viewport only — full-page requires JS evaluation which crashes
        //    Chromium under Rosetta x86 emulation; viewport screenshot is always safe)
        try {
            byte[] shot = page.screenshot();
            Allure.addAttachment("Failure Screenshot — " + testId, "image/png",
                    new ByteArrayInputStream(shot), ".png");
        } catch (Exception e) {
            log.warn("Could not capture failure screenshot: {}", e.getMessage());
        }

        // 2. DOM snapshot
        try {
            String dom = page.content();
            Allure.addAttachment("DOM Snapshot — " + testId, "text/html",
                    new ByteArrayInputStream(dom.getBytes(StandardCharsets.UTF_8)), ".html");
        } catch (Exception e) {
            log.warn("Could not capture DOM snapshot: {}", e.getMessage());
        }

        // 3. Browser console log
        if (!consoleMessages.isEmpty()) {
            String consoleDump = String.join("\n", consoleMessages);
            Allure.addAttachment("Browser Console — " + testId, "text/plain",
                    new ByteArrayInputStream(consoleDump.getBytes(StandardCharsets.UTF_8)), ".txt");
        }

        // 4. Viewport size
        try {
            com.microsoft.playwright.options.ViewportSize vp = page.viewportSize();
            if (vp != null) {
                String vpInfo = "width=" + vp.width + " height=" + vp.height;
                Allure.addAttachment("Viewport Size — " + testId, "text/plain",
                        new ByteArrayInputStream(vpInfo.getBytes(StandardCharsets.UTF_8)), ".txt");
            }
        } catch (Exception e) {
            log.warn("Could not capture viewport size: {}", e.getMessage());
        }

        // 5. Cookies / session state (values masked — session tokens are sensitive)
        try {
            String cookies = context.cookies().stream()
                    .map(c -> c.name + "=" + SensitiveDataMasker.MASK
                            + " [domain=" + c.domain + " path=" + c.path + "]")
                    .collect(java.util.stream.Collectors.joining("\n"));
            if (!cookies.isBlank()) {
                Allure.addAttachment("Cookies / Session State — " + testId, "text/plain",
                        new ByteArrayInputStream(cookies.getBytes(StandardCharsets.UTF_8)), ".txt");
            }
        } catch (Exception e) {
            log.warn("Could not capture cookies: {}", e.getMessage());
        }

        // 6. HAR network traffic (scrubbed — passwords/tokens removed from request bodies)
        try {
            if (harPath != null && Files.exists(harPath)) {
                String harJson = Files.readString(harPath, StandardCharsets.UTF_8);
                String scrubbed = SensitiveDataMasker.scrubJson(
                        SensitiveDataMasker.scrubFormEncoded(harJson));
                Allure.addAttachment("HAR Network Traffic — " + testId, "application/json",
                        new ByteArrayInputStream(scrubbed.getBytes(StandardCharsets.UTF_8)), ".har");
            }
        } catch (Exception e) {
            log.warn("Could not attach HAR: {}", e.getMessage());
        }

        // 7. Current URL + stack trace
        String diagnostics = buildDiagnosticsReport(testId, cause);
        Allure.addAttachment("Failure Diagnostics — " + testId, "text/plain",
                new ByteArrayInputStream(diagnostics.getBytes(StandardCharsets.UTF_8)), ".txt");
    }

    private String buildDiagnosticsReport(String testId, Throwable cause) {
        StringBuilder sb = new StringBuilder();
        sb.append("=== FAILURE DIAGNOSTICS ===\n");
        sb.append("Test ID    : ").append(testId).append("\n");
        sb.append("Current URL: ").append(page != null ? page.url() : "N/A").append("\n");
        sb.append("Browser    : ").append(BROWSER_KEY).append("\n");
        sb.append("Headless   : ").append(HEADLESS).append("\n");
        sb.append("Timeout    : ").append(TIMEOUT_MS).append("ms\n");
        try {
            com.microsoft.playwright.options.ViewportSize vp = page != null ? page.viewportSize() : null;
            sb.append("Viewport   : ").append(vp != null ? vp.width + "x" + vp.height : "N/A").append("\n");
        } catch (Exception ignored) {}
        sb.append("\n=== ROOT CAUSE ===\n");
        sb.append(cause.getClass().getName()).append(": ").append(cause.getMessage()).append("\n");
        for (StackTraceElement el : cause.getStackTrace()) {
            sb.append("  at ").append(el).append("\n");
        }
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // PER-STEP SCREENSHOT
    // -------------------------------------------------------------------------

    private void attachStepScreenshot(String action, String target) {
        try {
            // Viewport-only — full-page requires JS evaluation which crashes Chromium under Rosetta.
            byte[] screenshot = page.screenshot();
            Allure.addAttachment(action + ": " + target, "image/png",
                    new ByteArrayInputStream(screenshot), ".png");
        } catch (Exception e) {
            log.warn("Could not capture step screenshot: {}", e.getMessage());
        }
    }
}