package com.qa.ai.executor;

import com.qa.ai.config.SensitiveDataMasker;
import com.qa.ai.model.ApiAssertion;
import com.qa.ai.model.ApiRequest;
import com.qa.ai.model.TestCase;
import com.qa.ai.reporter.AgentActivity;
import io.qameta.allure.Allure;
import io.restassured.RestAssured;
import io.restassured.module.jsv.JsonSchemaValidator;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.testng.Assert;

import java.io.InputStream;
import java.util.List;
import java.util.Map;

/**
 * Executes API test cases generated by Claude using RestAssured.
 *
 * Each ApiAssertion type maps to a specific RestAssured/TestNG assertion.
 * The full request + response is attached to Allure for reporting.
 */
public class RestAssuredExecutor {

    private static final Logger log = LogManager.getLogger(RestAssuredExecutor.class);

    static {
        // Disable RestAssured logging to stdout — Log4j handles logging
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    // -------------------------------------------------------------------------
    // EXECUTE A TEST CASE
    // -------------------------------------------------------------------------

    /**
     * Runs a Claude-generated API test case via RestAssured.
     *
     * @param testCase a Claude-generated API test case
     */
    public void execute(TestCase testCase) {
        log.info("Executing API test: {}", testCase);

        Allure.step("Test: " + testCase.getTitle(), () -> {

            ApiRequest request = testCase.getRequest();
            if (request == null) {
                Assert.fail("API test case has no request object: " + testCase.getId());
            }

            // Build and send request
            Response response = sendRequest(request, testCase.getId());

            // Attach to Allure
            attachRequestResponse(testCase.getId(), request, response);

            // Run all assertions
            List<ApiAssertion> assertions = testCase.getAssertions();
            if (assertions != null) {
                for (ApiAssertion assertion : assertions) {
                    runAssertion(assertion, response, testCase.getId());
                }
            }

            log.info("API test PASSED: {}", testCase.getId());
        });
    }

    // -------------------------------------------------------------------------
    // BUILD AND SEND REQUEST
    // -------------------------------------------------------------------------

    // Track response time per test for SLA assertions
    private long lastResponseTimeMs = 0;

    private Response sendRequest(ApiRequest request, String testId) {
        log.debug("[{}] {} {}", testId, request.getMethod(), request.getUrl());

        RequestSpecification spec = RestAssured.given();

        // Query params
        if (request.getParams() != null && !request.getParams().isEmpty()) {
            spec = spec.queryParams(request.getParams());
            log.debug("[{}] Query params: {}", testId, request.getParams());
        }

        // Headers
        if (request.getHeaders() != null && !request.getHeaders().isEmpty()) {
            spec = spec.headers(request.getHeaders());
        } else {
            spec = spec.header("Content-Type", "application/json");
            spec = spec.header("Accept", "application/json");
        }

        // Body
        if (request.getBody() != null && !request.getBody().isBlank()) {
            spec = spec.body(request.getBody());
        }

        // Execute
        long start = System.currentTimeMillis();
        Response response = spec
                .when()
                .request(request.getMethod(), request.getUrl())
                .then()
                .extract().response();

        long elapsed = System.currentTimeMillis() - start;
        log.info("[{}] {} {} → status={} ({}ms)",
                testId, request.getMethod(), request.getUrl(),
                response.statusCode(), elapsed);

        lastResponseTimeMs = elapsed;
        AgentActivity.get().recordApiCall(testId, request.getMethod(), request.getUrl(), response.statusCode());

        // Attach response time to Allure
        Allure.addAttachment("Response Time — " + testId, "text/plain", elapsed + " ms");

        return response;
    }

    // -------------------------------------------------------------------------
    // ASSERTIONS
    // -------------------------------------------------------------------------

    private void runAssertion(ApiAssertion assertion, Response response, String testId) {
        String type     = assertion.getType();
        String path     = assertion.getPath();
        String expected = assertion.getExpected();

        log.debug("[{}] Asserting: type={} path={} expected={}", testId, type, path, expected);

        Allure.step(String.format("Assert %s: %s = %s", type, path, expected), () -> {
            switch (type) {
                case "status_code"    -> assertStatusCode(response, expected, testId);
                case "json_path"      -> assertJsonPath(response, path, expected, testId);
                case "header"         -> assertHeader(response, path, expected, testId);
                case "body_contains"  -> assertBodyContains(response, expected, testId);
                case "not_empty"      -> assertNotEmpty(response, path, testId);
                case "schema_file"    -> assertSchema(response, expected, testId);
                case "response_time_ms" -> assertResponseTime(expected, testId);
                default -> throw new IllegalArgumentException(
                        "Unknown assertion type: '" + type + "' — validator should have caught this");
            }
        });
    }

    private void assertStatusCode(Response response, String expected, String testId) {
        int expectedCode;
        try {
            expectedCode = Integer.parseInt(expected.trim());
        } catch (NumberFormatException e) {
            Assert.fail("[" + testId + "] status_code expected must be an integer, got: " + expected);
            return;
        }
        Assert.assertEquals(response.statusCode(), expectedCode,
                "[" + testId + "] Status code mismatch.");
    }

    private void assertJsonPath(Response response, String path, String expected, String testId) {
        Object actual;
        try {
            actual = response.jsonPath().get(path);
        } catch (Exception e) {
            Assert.fail("[" + testId + "] JsonPath '" + path + "' failed: " + e.getMessage());
            return;
        }
        Assert.assertNotNull(actual,
                "[" + testId + "] JsonPath '" + path + "' returned null. Body: " + response.body().asString());
        Assert.assertEquals(actual.toString(), expected,
                "[" + testId + "] JsonPath '" + path + "' value mismatch.");
    }

    private void assertHeader(Response response, String headerName, String expected, String testId) {
        String actual = response.header(headerName);
        Assert.assertNotNull(actual, "[" + testId + "] Header '" + headerName + "' is missing");
        Assert.assertTrue(actual.contains(expected),
                "[" + testId + "] Header '" + headerName + "' expected to contain '" + expected +
                "' but was: '" + actual + "'");
    }

    private void assertBodyContains(Response response, String expected, String testId) {
        String body = response.body().asString();
        Assert.assertTrue(body.contains(expected),
                "[" + testId + "] Body does not contain '" + expected + "'. Body: " + body);
    }

    private void assertNotEmpty(Response response, String path, String testId) {
        Object actual;
        try {
            actual = response.jsonPath().get(path);
        } catch (Exception e) {
            Assert.fail("[" + testId + "] JsonPath '" + path + "' failed: " + e.getMessage());
            return;
        }
        Assert.assertNotNull(actual, "[" + testId + "] JsonPath '" + path + "' was null/empty");
    }

    /**
     * Validates the response body against a JSON Schema file.
     *
     * @param expected  filename of the schema (e.g. "user.schema.json") — resolved from
     *                  src/main/resources/schemas/ on the classpath
     */
    private void assertSchema(Response response, String schemaFile, String testId) {
        log.debug("[{}] Validating response against schema: {}", testId, schemaFile);
        String schemaPath = "schemas/" + schemaFile;
        InputStream schemaStream = getClass().getClassLoader().getResourceAsStream(schemaPath);
        if (schemaStream == null) {
            Assert.fail("[" + testId + "] Schema file not found on classpath: " + schemaPath +
                        " — add it to src/main/resources/schemas/");
            return;
        }
        try {
            response.then().assertThat().body(JsonSchemaValidator.matchesJsonSchema(schemaStream));
            log.info("[{}] Schema validation passed for: {}", testId, schemaFile);
        } catch (AssertionError e) {
            Assert.fail("[" + testId + "] Schema validation failed against '" + schemaFile +
                        "': " + e.getMessage());
        }
    }

    /**
     * Asserts that the last API response time was below a threshold.
     *
     * @param expected  threshold in milliseconds as a string (e.g. "2000")
     */
    private void assertResponseTime(String expected, String testId) {
        long threshold;
        try {
            threshold = Long.parseLong(expected.trim());
        } catch (NumberFormatException e) {
            Assert.fail("[" + testId + "] response_time_ms expected must be an integer (ms), got: " + expected);
            return;
        }
        log.debug("[{}] Response time assertion: {}ms actual vs {}ms threshold", testId, lastResponseTimeMs, threshold);
        Assert.assertTrue(lastResponseTimeMs <= threshold,
                String.format("[%s] Response time %dms exceeded SLA threshold of %dms",
                        testId, lastResponseTimeMs, threshold));
    }

    // -------------------------------------------------------------------------
    // ALLURE ATTACHMENT
    // -------------------------------------------------------------------------

    private void attachRequestResponse(String testId, ApiRequest request, Response response) {
        String detail = buildRequestResponseDetail(request, response);
        Allure.addAttachment("API Request & Response — " + testId, "text/plain", detail);
        log.debug("[{}] Request/response attached to Allure", testId);
    }

    private String buildRequestResponseDetail(ApiRequest request, Response response) {
        StringBuilder sb = new StringBuilder();
        sb.append("=== REQUEST ===\n");
        sb.append(request.getMethod()).append(" ").append(request.getUrl()).append("\n");

        if (request.getParams() != null && !request.getParams().isEmpty()) {
            sb.append("Query Params: ").append(request.getParams()).append("\n");
        }
        if (request.getHeaders() != null && !request.getHeaders().isEmpty()) {
            sb.append("Headers:\n");
            request.getHeaders().forEach((k, v) ->
                sb.append("  ").append(k).append(": ")
                  .append(SensitiveDataMasker.maskIfSensitive(k, v)).append("\n"));
        }
        if (request.getBody() != null && !request.getBody().isBlank()) {
            sb.append("Body:\n").append(SensitiveDataMasker.scrubJson(
                    SensitiveDataMasker.scrubFormEncoded(request.getBody()))).append("\n");
        }

        sb.append("\n=== RESPONSE ===\n");
        sb.append("Status : ").append(response.statusCode()).append("\n");

        Map<String, String> headers = response.headers().asList().stream()
                .collect(java.util.stream.Collectors.toMap(
                        h -> h.getName(), h -> h.getValue(), (a, b) -> a));
        sb.append("Headers: ").append(headers).append("\n");
        sb.append("Body:\n").append(response.body().prettyPrint());

        sb.append("\n\n=== cURL REPRODUCTION ===\n");
        sb.append(buildCurlCommand(request));

        return sb.toString();
    }

    private String buildCurlCommand(ApiRequest request) {
        StringBuilder curl = new StringBuilder("curl -X ").append(request.getMethod());

        // URL with query params inlined
        String url = request.getUrl();
        if (request.getParams() != null && !request.getParams().isEmpty()) {
            StringBuilder query = new StringBuilder();
            request.getParams().forEach((k, v) -> {
                if (query.length() > 0) query.append("&");
                query.append(k).append("=").append(v);
            });
            url = url + (url.contains("?") ? "&" : "?") + query;
        }
        curl.append(" \"").append(url).append("\"");

        // Headers
        if (request.getHeaders() != null && !request.getHeaders().isEmpty()) {
            request.getHeaders().forEach((k, v) ->
                curl.append(" \\\n  -H \"").append(k).append(": ")
                    .append(SensitiveDataMasker.maskIfSensitive(k, v)).append("\""));
        } else {
            curl.append(" \\\n  -H \"Content-Type: application/json\"");
            curl.append(" \\\n  -H \"Accept: application/json\"");
        }

        // Body
        if (request.getBody() != null && !request.getBody().isBlank()) {
            String escaped = request.getBody().replace("'", "'\\''");
            curl.append(" \\\n  -d '").append(escaped).append("'");
        }

        return curl.toString();
    }
}
